#include "board.h"
#include "constants.h"

namespace Chess {

Board::Board() {
  m_bitboards[WHITE_PAWN_IDX] = WHITE_PAWN_INITIAL_POSITION;
  m_bitboards[WHITE_KNIGHT_IDX] = WHITE_KNIGHT_INITIAL_POSITION;
  m_bitboards[WHITE_BISHOP_IDX] = WHITE_BISHOP_INITIAL_POSITION;
  m_bitboards[WHITE_ROOK_IDX] = WHITE_ROOK_INITIAL_POSITION;
  m_bitboards[WHITE_QUEEN_IDX] = WHITE_QUEEN_INITIAL_POSITION;
  m_bitboards[WHITE_KING_IDX] = WHITE_KING_INITIAL_POSITION;

  m_bitboards[BLACK_PAWN_IDX] = BLACK_PAWN_INITIAL_POSITION;
  m_bitboards[BLACK_KNIGHT_IDX] = BLACK_KNIGHT_INITIAL_POSITION;
  m_bitboards[BLACK_BISHOP_IDX] = BLACK_BISHOP_INITIAL_POSITION;
  m_bitboards[BLACK_ROOK_IDX] = BLACK_ROOK_INITIAL_POSITION;
  m_bitboards[BLACK_QUEEN_IDX] = BLACK_QUEEN_INITIAL_POSITION;
  m_bitboards[BLACK_KING_IDX] = BLACK_KING_INITIAL_POSITION;
}

} // namespace Chess